version: '3.1'
services:
  bot:
    restart: unless-stopped
    image: node:lts
    command: 'node index.js'
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - './dbdata:/data/db'